include Makefile.config

RPM ?= $(HOME)/rpm

build: 
	make -C lst build

check:
	make -C lst check

clean:
	rm -f *~
	make -C lst clean

install: build
	install -d $(bindir) $(sbindir) $(dir)
	make -C lst install
	install update-ldetect-lst $(sbindir)
	install convert/merge2pcitable.pl $(bindir)

rpm: srpm
	rpm -bb --clean --rmsource --rmspec $(RPM)/SPECS/$(project).spec
	cvs commit

srpm: check clean $(RPM)
	cvs update
	(echo "# !! DON'T MODIFY HERE, MODIFY IN THE CVS !!" ; \
         cat $(project).spec \
        ) > $(RPM)/SPECS/$(project).spec

	(cd .. ; tar cfj $(RPM)/SOURCES/$(project).tar.bz2 $(project))
	rpm -bs $(RPM)/SPECS/$(project).spec

changelog:
	cvs2cl -U ../common/username -I ChangeLog 
	rm -f ChangeLog.bak
	cvs commit -m "Generated by cvs2cl the `date '+%d_%b'`" ChangeLog
